# Storage Class

kind: StorageClass
apiVersion: storage.k8s.io/v1

metadata:
  labels:
    app: influxdb
  name: influxdb-sc
  namespace: influxdb-ns

provisioner: k8s.io/minikube-hostpath
volumeBindingMode: Immediate

parameters:
 type: gp2 # This configures SSDs

allowVolumeExpansion: true
reclaimPolicy: Retain
---

# PV

apiVersion: v1
kind: PersistentVolume

metadata:
  labels:
    app: influxdb
  name: influxdb-pv
  namespace: influxdb-ns
  labels:
    type: local

spec:
  storageClassName: influxdb-sc
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/home/kube/influxdb-files/volume-files"
---
~
