# Namespace

apiVersion: v1
kind: Namespace
metadata:
  name: telegraf-ns
---


# Secret

apiVersion: v1
kind: Secret
metadata:
  name: telegraf-secrets
  namespace: telegraf-ns
type: Opaque
stringData:
  INFLUXDB_URL: http://10.40.0.132:30015
  INFLUXDB_BUCKET: eta
  INFLUXDB_ORGANIZATION: eta
  INFLUXDB_TOKEN: uUeleZTGA_1kLfSLSmRHzyl9LFHYtkfg-EiBcvmlBhxLh94vPgtTO0_CyNPe6sZoSn0Oyx74pG5Qy5iIPmmm_w==
  VCENTER_URL: https://10.40.0.5/sdk
  VCENTER_USERNAME: dpiroi@eta2u.demo
  VCENTER_PASSWORD: <password>

---


# ConfigMap

apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-config
  namespace: telegraf-ns
data:
  telegraf.conf: |+
    ## Input <- vSphere
    ## Realtime instance
    [[inputs.vsphere]]
    interval = "20s"
      vcenters = ["$VCENTER_URL"]
      username = "$VCENTER_USERNAME"
      password = "$VCENTER_PASSWORD"
    vm_metric_include = []
    host_metric_include = []
    cluster_metric_exclude = [""]
    datastore_metric_exclude = [""]
    max_query_metrics = 256
    timeout = "60s"
    insecure_skip_verify = true
    ## Historical instance
    [[inputs.vsphere]]
    interval = "300s"
      vcenters = ["$VCENTER_URL"]
      username = "$VCENTER_USERNAME"
      password = "$VCENTER_PASSWORD"
    datastore_metric_include = [ "disk.capacity.latest", "disk.used.latest", "disk.provisioned.latest"]
    insecure_skip_verify = true
    force_discover_on_init = true
    cluster_metric_include = [""]
    datacenter_metric_include = [""]
    host_metric_exclude = [""] # Exclude realtime metrics
    vm_metric_exclude = [""] # Exclude realtime metrics
    max_query_metrics = 256
    collect_concurrency = 3
    ## Output -> InfluxDB
    [[outputs.influxdb_v2]]
      urls = ["$INFLUXDB_URL"]
      token = "$INFLUXDB_TOKEN"
      organization = "$INFLUXDB_ORGANIZATION"
      bucket = "$INFLUXDB_BUCKET"
---


# Deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: telegraf-ns
  name: telegraf
spec:
  selector:
    matchLabels:
      app: telegraf
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      containers:
        - image: telegraf:latest
          name: telegraf
          envFrom:
            - secretRef:
                name: telegraf-secrets
          volumeMounts:
            - name: telegraf-config-volume
              mountPath: /etc/telegraf/telegraf.conf
              subPath: telegraf.conf
              readOnly: true
      volumes:
        - name: telegraf-config-volume
          configMap:
            name: telegraf-config
---
